spring:
  application:
    name: CLIENTE-SERVICE
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: 8089
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
